FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir streamlit==1.39.0 requests==2.32.3 python-dotenv==1.0.1

COPY app/frontend ./app/frontend
COPY models ./models

EXPOSE 8501

ENV API_URL=http://backend:8000

CMD ["streamlit", "run", "app/frontend/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]


